[connections.supabase]
SUPABASE_URL = "https://azryutrztuxzsfkvelkh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6cnl1dHJ6dHV4enNma3ZlbGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTY1NDYxOTAsImV4cCI6MjAzMjEyMjE5MH0.Gw9QOe2b2Ik-qa1YnLufpPcyq2TlirnUBNOR7KaW7dk"


SUPABASE_URL = "https://azryutrztuxzsfkvelkh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6cnl1dHJ6dHV4enNma3ZlbGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTY1NDYxOTAsImV4cCI6MjAzMjEyMjE5MH0.Gw9QOe2b2Ik-qa1YnLufpPcyq2TlirnUBNOR7KaW7dk"
