[connections.supabase]
SUPABASE_URL = "https://kzygmjhqqcvruljhrgvb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eWdtamhxcWN2cnVsamhyZ3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU5NzM4MzUsImV4cCI6MjAzMTU0OTgzNX0.f6WT8jQTILHvP5TzavdSt282sNAfGzrm75VFQ_VNzOA"